export const products = [
  {
    id: 1,
    name: "Увлажняющий мусс",
    description: "Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.",
    composition: [
      "активные натуральные комплексы",
      "витамины С, А, РР, В И Е",
      "солнцезащитные компоненты",
    ],
    price: 2750,
    image: "images/moisturizing-mousse.png",
    skinType: "для нормальной кожи",
    category: "Уход за лицом",
  },
  {
    id: 2,
    name: "Увлажняющая маска",
    description: "Способствует удерживанию влаги в верхних слоях кожи.",
    composition: ["воски", "минералы", "масла"],
    price: 3500,
    image: "images/moisturizing-mask.png",
    skinType: "для нормальной кожи",
    category: "Маски",
  },
  {
    id: 3,
    name: "Гель для умывания",
    description: "Интенсивно очищает, не повреждает защитный барьер кожи.",
    composition: [
      "минералы",
      "витамины С, А, РР, В И Е",
      "солнцезащитные компоненты",
    ],
    price: 1650,
    image: "images/cleansing-gel.png",
    skinType: "для нормальной кожи",
    category: "Очищение",
  },
  {
    id: 4,
    name: "Подарочный набор №1",
    description: "Набор, состоящий из увлажняющего крема и маски.",
    composition: ["воски", "минералы", "масла"],
    price: 4750,
    image: "images/cift-set.png",
    skinType: "для нормальной кожи",
    category: "Наборы",
  },
  {
    id: 5,
    name: "Подарочный набор №5",
    description:
      "Весь набор средств Invisible symphony, крем, маска, мусс и гель",
    composition: [
      "активные натуральные комплексы",
      "витамины С, А, РР, В И Е",
      "солнцезащитные компоненты",
    ],
    price: 7520,
    image: "images/cift-seta.png",
    skinType: "для нормальной кожи",
    category: "Наборы",
  },
];
